google:
  application_name: "GRAiS"
  credentials_file: "credentials.json"
  token_file: "~/.config/grais/google_token.json"

  scopes:
    gmail:
      - https://www.googleapis.com/auth/gmail.readonly
      - https://www.googleapis.com/auth/gmail.send

    calendar:
      - https://www.googleapis.com/auth/calendar

    drive: # To be added later
      - https://www.googleapis.com/auth/drive.readonly
